export const INPUT_TYPE_LIST = 'list';
export const INPUT_TYPE_TEXT = 'text';
export const INPUT_TYPE_NUMBER = 'number';
export const INPUT_TYPE_DATETIME = 'datetime';
export const INPUT_TYPE_USERLIST = 'userlist';

export const MAP_COLOR_GREEN = '3, 252, 115';
export const MAP_COLOR_PRIMARY = '125, 52, 235';

export const NONE_KEY = '-';
export const EMPTY = '';

export const EVENT_FLEET_GPS_UPDATE = 'fleet-gps-update';
export const EVENT_FLEET_GPS_REQUEST = 'fleet-gps-request';
export const PASSENGER_NOTIF = 'passengerNotif';

export const MODE_AREAL = 'areal';
export const MODE_PASSENGER = 'passenger';
export const MODE_DRIVER = 'driver';

export const SCREEN_SM = 640;
export const SCREEN_MD = 768;
export const SCREEN_LG = 1024;
export const SCREEN_XL = 1280;
export const SCREEN_2XL = 1536;

export const LOGIN_PAGE = '/auth/signin';

export const PERMIT_PASSENGER_SERVICE = 'SERVICE.PERSONAL';
export const PERMIT_PASSENGER_LOCATION = 'LOCATION.PERSONAL';

export const PERMIT_DRIVER = 'DRIVER';
export const PERMIT_SERVICE = 'SERVICE.ORG';

export const PERMIT_SERVICE_PERSONAL_SUBMIT = 'SERVICE.PERSONAL.SUBMIT';
export const PERMIT_SERVICE_ORG_DIRECT_SUBMIT = 'SERVICE.ORG.DIRECT_SUBMIT';
export const PERMIT_SERVICE_PERSONAL_EDIT = 'SERVICE.PERSONAL.EDIT';
export const PERMIT_SERVICE_ORG_DIRECT_EDIT = 'SERVICE.ORG.DIRECT_EDIT';
export const PERMIT_SERVICE_ORG_REQUEST_APPROVAL = 'SERVICE.ORG.DIRECT_EDIT';



export const PERMIT_DASHBOARD = 'DASHBOARD'
// export const PERMIT_ONLYADMIN='ONLYADMIN'
export const PERMIT_RESTRICTION = 'RESTRICTION';



//AGANCE

export const PERMIT_AGANCE_AGANCE_CREATE = 'AGANCE.AGANCE.CREATE';
export const PERMIT_AGANCE_AGANCE_EDIT = 'AGANCE.AGANCE.EDIT';
export const PERMIT_AGANCE_AGANCE_DELETE = 'AGANCE.AGANCE.DELETE';
export const PERMIT_AGANCE_AGANCE_LIST = 'AGANCE.AGANCE.LIST';

export const PERMIT_AGANCE_SODURE_PARVANE_CREATE = 'AGANCE.SODURE_PARVANE';
export const PERMIT_AGANCE_SODURE_PARVANE_EDIT = 'AGANCE.SODURE_PARVANE';
export const PERMIT_AGANCE_SODURE_PARVANE_DELETE = 'AGANCE.SODURE_PARVANE';
export const PERMIT_AGANCE_SODURE_PARVANE_LIST = 'AGANCE.SODURE_PARVANE';

export const PERMIT_AGANCE_DRIVER_CREATE = 'AGANCE.DRIVER.CREATE';
export const PERMIT_AGANCE_DRIVER_EDIT = 'AGANCE.DRIVER.EDIT';
export const PERMIT_AGANCE_DRIVER_DELETE = 'AGANCE.DRIVER.DELETE';
export const PERMIT_AGANCE_DRIVER_LIST = 'AGANCE.DRIVER.LIST';

export const PERMIT_AGANCE_CART_SALAHIYAT_CREATE = 'AGANCE.CART_SALAHIYAT.CREATE';
export const PERMIT_AGANCE_CART_SALAHIYAT_EDIT = 'AGANCE.CART_SALAHIYAT.EDIT';
export const PERMIT_AGANCE_CART_SALAHIYAT_DELETE = 'AGANCE.CART_SALAHIYAT.DELETE';
export const PERMIT_AGANCE_CART_SALAHIYAT_LIST = 'AGANCE.CART_SALAHIYAT.LIST';

export const PERMIT_AGANCE_TAMDID_CART_SALAHIYAT_CREATE = 'AGANCE.TAMDID_CART_SALAHIYAT.CREATE';
export const PERMIT_AGANCE_TAMDID_CART_SALAHIYAT_EDIT = 'AGANCE.TAMDID_CART_SALAHIYAT.EDIT';
export const PERMIT_AGANCE_TAMDID_CART_SALAHIYAT_DELETE = 'AGANCE.TAMDID_CART_SALAHIYAT.DELETE';
export const PERMIT_AGANCE_TAMDID_CART_SALAHIYAT_LIST = 'AGANCE.TAMDID_CART_SALAHIYAT.LIST';

export const PERMIT_AGANCE_ESTELAMHAYE_SE_GANE_CREATE = 'AGANCE.ESTELAMHAYE_SE_GANE.CREATE';
export const PERMIT_AGANCE_ESTELAMHAYE_SE_GANE_EDIT = 'AGANCE.ESTELAMHAYE_SE_GANE.EDIT';
export const PERMIT_AGANCE_ESTELAMHAYE_SE_GANE_DELETE = 'AGANCE.ESTELAMHAYE_SE_GANE.DELETE';
export const PERMIT_AGANCE_ESTELAMHAYE_SE_GANE_LIST = 'AGANCE.ESTELAMHAYE_SE_GANE.LIST';

export const PERMIT_AGANCE_ESTELAM_AMAKEN_CREATE = 'AGANCE.ESTELAM_AMAKEN.CREATE';
export const PERMIT_AGANCE_ESTELAM_AMAKEN_EDIT = 'AGANCE.ESTELAM_AMAKEN.EDIT';
export const PERMIT_AGANCE_ESTELAM_AMAKEN_DELETE = 'AGANCE.ESTELAM_AMAKEN.DELETE';
export const PERMIT_AGANCE_ESTELAM_AMAKEN_LIST = 'AGANCE.ESTELAM_AMAKEN.LIST';

export const PERMIT_AGANCE_MOAYENE_FANI_CREATE = 'AGANCE.MOAYENE_FANI.CREATE';
export const PERMIT_AGANCE_MOAYENE_FANI_EDIT = 'AGANCE.MOAYENE_FANI.EDIT';
export const PERMIT_AGANCE_MOAYENE_FANI_DELETE = 'AGANCE.MOAYENE_FANI.DELETE';
export const PERMIT_AGANCE_MOAYENE_FANI_LIST = 'AGANCE.MOAYENE_FANI.LIST';


export const PERMIT_AGANCE_TAREFE_AVAREZ_CREATE = 'AGANCE.TAREFE_AVAREZ.CREATE';
export const PERMIT_AGANCE_TAREFE_AVAREZ_EDIT = 'AGANCE.TAREFE_AVAREZ.EDIT';
export const PERMIT_AGANCE_TAREFE_AVAREZ_DELETE = 'AGANCE.TAREFE_AVAREZ.DELETE';
export const PERMIT_AGANCE_TAREFE_AVAREZ_LIST = 'AGANCE.TAREFE_AVAREZ.LIST';

export const PERMIT_AGANCE_DABIRKHANE_CREATE = 'AGANCE.DABIRKHANE.CREATE';
export const PERMIT_AGANCE_DABIRKHANE_EDIT = 'AGANCE.DABIRKHANE.EDIT';
export const PERMIT_AGANCE_DABIRKHANE_DELETE = 'AGANCE.DABIRKHANE.DELETE';
export const PERMIT_AGANCE_DABIRKHANE_LIST = 'AGANCE.DABIRKHANE.LIST';

export const PERMIT_AGANCE_PROFILE_CREATE = 'AGANCE.PROFILE.CREATE';
export const PERMIT_AGANCE_PROFILE_EDIT = 'AGANCE.PROFILE.EDIT';
export const PERMIT_AGANCE_PROFILE_DELETE = 'AGANCE.PROFILE.DELETE';
export const PERMIT_AGANCE_PROFILE_LIST = 'AGANCE.PROFILE.LIST';

//AGANCE

export const PERMIT_LOCATION = 'LOCATION.ORG';
export const PERMIT_USERS_CREATE = 'USERS.CREATE';
export const PERMIT_USERS_EDIT = 'USERS.EDIT';
export const PERMIT_USERS_DELETE = 'USERS.DELETE';
export const PERMIT_USERS_LIST = 'USERS.LIST';

export const PERMIT_VEHICLES_CREATE = 'VEHICLES.CREATE';
export const PERMIT_VEHICLES_DELETE = 'VEHICLES.DELETE';
export const PERMIT_VEHICLES_EDIT = 'VEHICLES.EDIT';
export const PERMIT_VEHICLES_LIST = 'VEHICLES.LIST';


export const PERMIT_DEFINITIONS_CAR_COLORS = 'DEFINITIONS.CAR_COLORS';
export const PERMIT_DEFINITIONS_CAR_TYPES = 'DEFINITIONS.CAR_TYPES';
export const PERMIT_DEFINITIONS_CAR_NAME = 'DEFINITIONS.CAR_NAME';
export const PERMIT_DEFINITIONS_SERVICE_TYPES = 'DEFINITIONS.SERVICE_TYPES';

export const PERMIT_AREAS = 'AREAS';
export const PERMIT_DEFINITIONS = 'DEFINITIONS';
export const PERMIT_RULES = 'RULES';
export const PERMIT_DELEGATION = 'DELEGATION';

export const PERMIT_REPORTS = 'REPORTS';


export const PERMIT_AREAS_CREATE = 'AREAS.CREATE';
export const PERMIT_AREAS_EDIT = 'AREAS.EDIT';
export const PERMIT_AREAS_DELETE = 'AREAS.DELETE';
export const PERMIT_AREAS_LIST = 'AREAS.LIST';

export const VEHICLE_TYPE_AGENCY = 'agency';
export const VEHICLE_TYPE_ORG = 'org';



export const DB_ROLE_DRIVER_TITLE='راننده'
export const DB_ROLE_MOSAFER_TITLE='مسافر'
export const DB_ROLE_ADMIN_TITLE='مدیر سیستم'
export const DB_ROLE_DISPATURE_TITLE='دیسپاچر'
export const DB_ROLE_MODIR_PROJECT_TITLE='مدیر پروژه'